"""Suporte a 2FA

Revision ID: 028ff68a42e7
Revises: 087ac848122c
Create Date: 2025-09-18 02:47:46.115314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028ff68a42e7'
down_revision = '087ac848122c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usa_2fa', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('_otp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('ultimo_otp', sa.String(length=6), nullable=True))

    op.create_table('backup2fa',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hash_codigo', sa.String(length=256), nullable=False),
                    sa.Column('usuario_id', sa.Uuid(), nullable=True),
                    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup2fa')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ultimo_otp')
        batch_op.drop_column('_otp_secret')
        batch_op.drop_column('usa_2fa')

    # ### end Alembic commands ###
