"""Suporte a foto do usuario

Revision ID: 087ac848122c
Revises: b1ec9dad1f9d
Create Date: 2025-09-17 17:24:36.541910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087ac848122c'
down_revision = 'b1ec9dad1f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('com_foto', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('foto_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto_mime', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_mime')
        batch_op.drop_column('foto_base64')
        batch_op.drop_column('com_foto')

    # ### end Alembic commands ###
