"""Codigos 2FA de backup

Revision ID: 16db66d5cb96
Revises: 25e9cf188f41
Create Date: 2025-09-18 20:14:09.345817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16db66d5cb96'
down_revision = '25e9cf188f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup2fa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_codigo', sa.String(length=256), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup2fa')
    # ### end Alembic commands ###
