"""alterando os campos ids de int para uuid

Revision ID: 1b053607c90f
Revises: ba70b2a981e9
Create Date: 2025-10-07 17:24:51.437053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b053607c90f'
down_revision = 'ba70b2a981e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.alter_column('filme_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('filmes_generos', schema=None) as batch_op:
        batch_op.alter_column('filme_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('genero_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)

    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal', sa.Boolean(), nullable=False))
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('principal')

    with op.batch_alter_table('filmes_generos', schema=None) as batch_op:
        batch_op.alter_column('genero_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('filme_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('filme_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
