"""Adicao do avatar do usuario

Revision ID: 25e9cf188f41
Revises: 028ff68a42e7
Create Date: 2025-09-18 15:26:45.257245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e9cf188f41'
down_revision = '028ff68a42e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_base64', sa.Text(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('avatar_base64')

    # ### end Alembic commands ###
