"""criação do model de filmes

Revision ID: 2933145e8a0e
Revises: 25e9cf188f41
Create Date: 2025-09-28 14:01:57.506513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2933145e8a0e'
down_revision = '25e9cf188f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=250), nullable=False),
    sa.Column('titulo_nacional', sa.String(length=250), nullable=False),
    sa.Column('ano_lancamento', sa.Integer(), nullable=False),
    sa.Column('lancado', sa.Boolean(), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('orcamento', sa.DECIMAL(), nullable=True),
    sa.Column('faturamento_lancamento', sa.DECIMAL(precision=2), nullable=True),
    sa.Column('poster_principal', sa.Text(), nullable=True),
    sa.Column('link_trailer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('usa_2fa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(false)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('usa_2fa',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(false)'))

    op.drop_table('filmes')
    # ### end Alembic commands ###
