"""criando do domínio de dados de pessoas atores e participaçoes

Revision ID: 8e6115e1a17f
Revises: 1b053607c90f
Create Date: 2025-10-07 17:28:36.174217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6115e1a17f'
down_revision = '1b053607c90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcoes_tecnicas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('categoria', sa.String(length=250), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sexos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('nacionalidade', sa.String(length=60), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('avatar_base64', sa.Text(), nullable=True),
    sa.Column('sexo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['sexo_id'], ['sexos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome_artistico', sa.String(length=250), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id')
    )
    op.create_table('participacoes',
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('inicio_trabalho', sa.Date(), nullable=True),
    sa.Column('fim_trabalho', sa.Date(), nullable=True),
    sa.Column('remuneracao', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('funcao_tecnica_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['funcao_tecnica_id'], ['funcoes_tecnicas.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('filme_id', 'pessoa_id')
    )
    op.create_table('atuacoes',
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('ator_id', sa.Uuid(), nullable=False),
    sa.Column('papel', sa.String(length=250), nullable=False),
    sa.Column('protagonista', sa.Boolean(), nullable=False),
    sa.Column('orcamento', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('tempo_tela', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ator_id'], ['atores.id'], ),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.PrimaryKeyConstraint('filme_id', 'ator_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atuacoes')
    op.drop_table('participacoes')
    op.drop_table('atores')
    op.drop_table('pessoas')
    op.drop_table('sexos')
    op.drop_table('funcoes_tecnicas')
    # ### end Alembic commands ###
