"""criação dos relacionamentos das avaliações

Revision ID: ba70b2a981e9
Revises: fdb300d63f87
Create Date: 2025-10-04 23:39:10.917376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba70b2a981e9'
down_revision = 'fdb300d63f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacoes',
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.DECIMAL(precision=1, scale=2), nullable=True),
    sa.Column('data_avaliacao', sa.Date(), server_default='NOW()', nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('recomenda', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('filme_id', 'usuario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliacoes')
    # ### end Alembic commands ###
