"""inicial

Revision ID: f4f18a708240
Revises: 
Create Date: 2025-10-28 23:12:22.648227

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f4f18a708240'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('titulo_original', sa.String(length=250), nullable=False),
                    sa.Column('titulo_nacional', sa.String(length=250), nullable=False),
                    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
                    sa.Column('lancado', sa.Boolean(), server_default='False', nullable=False),
                    sa.Column('duracao', sa.Integer(), nullable=True),
                    sa.Column('sinopse', sa.Text(), nullable=True),
                    sa.Column('poster_base64', sa.Text(), nullable=True),
                    sa.Column('poster_mime', sa.String(length=32), nullable=True),
                    sa.Column('orcamento', sa.DECIMAL(precision=10, scale=2), nullable=True),
                    sa.Column('faturamento_lancamento', sa.DECIMAL(precision=10, scale=2), nullable=True),
                    sa.Column('link_trailer', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('funcoes_tecnicas',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('nome', sa.String(length=250), nullable=False),
                    sa.Column('descricao', sa.Text(), nullable=False),
                    sa.Column('ativa', sa.Boolean(), server_default='true', nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('funcoes_tecnicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcoes_tecnicas_nome'), ['nome'], unique=True)

    op.create_table('generos',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('nome', sa.String(length=250), nullable=False),
                    sa.Column('descricao', sa.Text(), nullable=False),
                    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generos_nome'), ['nome'], unique=True)

    op.create_table('pessoas',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('nome', sa.String(length=200), nullable=False),
                    sa.Column('nacionalidade', sa.String(length=100), nullable=True),
                    sa.Column('nascimento', sa.Date(), nullable=True),
                    sa.Column('biografia', sa.Text(), nullable=True),
                    sa.Column('foto_base64', sa.Text(), nullable=True),
                    sa.Column('avatar_base64', sa.Text(), nullable=True),
                    sa.Column('e_ator', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('sexo', sa.String(length=1), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    from moviedb.models.custom_types import EncryptedType
    op.create_table('usuarios',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('nome', sa.String(length=60), nullable=False),
                    sa.Column('email_normalizado', sa.String(length=180), nullable=False),
                    sa.Column('password_hash', sa.String(length=256), nullable=False),
                    sa.Column('ativo', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('dta_validacao_email', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('com_foto', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('foto_base64', sa.Text(), nullable=True),
                    sa.Column('avatar_base64', sa.Text(), nullable=True),
                    sa.Column('foto_mime', sa.String(length=32), nullable=True),
                    sa.Column('usa_2fa', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('_otp_secret', EncryptedType(length=500), nullable=True),
                    sa.Column('ultimo_otp', sa.String(length=6), nullable=True),
                    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email_normalizado'), ['email_normalizado'], unique=True)

    op.create_table('atores',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('nome_artistico', sa.String(length=200), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['pessoas.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('avaliacoes',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('filme_id', sa.Uuid(), nullable=False),
                    sa.Column('usuario_id', sa.Uuid(), nullable=False),
                    sa.Column('nota', sa.Integer(), nullable=False),
                    sa.Column('comentario', sa.Text(), nullable=True),
                    sa.Column('recomenda', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
                    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('backup2fa',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('hash_codigo', sa.String(length=256), nullable=False),
                    sa.Column('usuario_id', sa.Uuid(), nullable=False),
                    sa.Column('utilizado', sa.Boolean(), server_default='false', nullable=False),
                    sa.Column('dta_uso', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('dta_para_remocao', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup2fa_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('equipes_tecnicas',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('filme_id', sa.Uuid(), nullable=False),
                    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
                    sa.Column('funcao_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
                    sa.ForeignKeyConstraint(['funcao_id'], ['funcoes_tecnicas.id'], ),
                    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('filmes_generos',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('filme_id', sa.Uuid(), nullable=False),
                    sa.Column('genero_id', sa.Uuid(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
                    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('filme_id', 'genero_id')
                    )
    op.create_table('atuacoes',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('filme_id', sa.Uuid(), nullable=False),
                    sa.Column('ator_id', sa.Uuid(), nullable=False),
                    sa.Column('personagem', sa.String(length=100), server_default='as him/herself', nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['ator_id'], ['atores.id'], ),
                    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('filme_id', 'ator_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atuacoes')
    op.drop_table('filmes_generos')
    op.drop_table('equipes_tecnicas')
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup2fa_usuario_id'))

    op.drop_table('backup2fa')
    op.drop_table('avaliacoes')
    op.drop_table('atores')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email_normalizado'))

    op.drop_table('usuarios')
    op.drop_table('pessoas')
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generos_nome'))

    op.drop_table('generos')
    with op.batch_alter_table('funcoes_tecnicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcoes_tecnicas_nome'))

    op.drop_table('funcoes_tecnicas')
    op.drop_table('filmes')
    # ### end Alembic commands ###
